// frontend/nuxt/pages/ssr/index.vue
<template>
  <div>
    <h1>Client Side Rendering Example</h1>
    <div>
      <p>Id: {{ data?.id }}</p>
      <p>Title: {{ data?.title }}</p>
      <p>UserId: {{ data?.userId }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
const { data } = (await useAsyncData("run_useAsyncData", () => {
  return $fetch("https://jsonplaceholder.typicode.com/todos/1");
})) as { data: Ref<Record<string, string>> };
</script>

// frontend/next/app/ssr/page.tsx
interface SsrTodo {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}

export default async function SsrPage() {
  const todo: SsrTodo = await getData();

  console.log(todo);
  return (
    <ul>
      <li> Id : {todo.id}</li>
      <li> userId : {todo.userId}</li>
      <li> title : {todo.title}</li>
      <li> completed : {todo.completed.toString()}</li>
    </ul>
  );
}

async function getData() {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos/1");
  return res.json();
}
